### ISSUE TITLE
Please remove auto-jump feature from supremium armor

### ISSUE THREAD

**Issue by croftyraider** [BlakeBr0/MysticalAgriculture#131]
Me again, playing in 1.12.2 now. Did you know that Auto-Jump is an option in Vanilla Minecraft? Which means the user can choose whether or not they want it. http://prntscr.com/hto0on

Your armor is forcing it on even though I have it disabled.

Could you please remove this ability from 1.12.2 since it's redundant? And breaks the users ability to play the game the way they want to?

Thanks.

**Comment by BlakeBr0** [comment]
Auto jump and step assist are different. Auto jump makes you jump and step assist makes you step up larger heights. You can disable set bonuses in the config and it'll still keep the flight from supremium armor. It's not redundant because myself and most other people actually find step assist to be a useful mechanic.

**Comment by croftyraider** [comment]
TIL that auto-jump and step-assist are different, though for the life of me I can't say I've experienced a difference. Thanks for the tip on the config rule to change to turn whatever it is off. Greatly appreciated!

**Comment by BlakeBr0** [comment]
A better explanation of the difference would be that step assist is basically just making it so you can walk up a full block like you can with a half block normally, while auto jump is jumping.
