### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by General-Nonsense** [BlakeBr0/MysticalAgriculture#182]
I know the mod is pretty self explanatory, and this isnt a real need, but could you add a wiki here? It would be nice to have some more in-depth information about the items. like, how exactly does the growth accelerator work? what is the radius of the scythe, what does the sickle do? it would be nice to have some information, because it is kinda hard to find, and it would be cool to get a more in-depth look at how items work.

**Comment by MentalMouse** [comment]
There used to be a forum thread, but I couldn't find it just now.

**Comment by Hexxonite** [comment]
Hi, Im playing with this Mod on Enigmatica 2 Expert for the first time and cant figure out alot of stuff. 
I am starting to build an ME System but need the Certus Quartz Essence for that, which doesnt have a reasonable recipe and or wiki page. Also what about the Prosperity Ore? If I go into the "World Gen" JEI Tab, it shows up only for "Kelt-4ab", "Uranus" and "Neptune", which I dont have access to yet. 

Nothing against this Mod but I'm more into the technical/mechnical part of the pack rather than plants and stuff, so I would like to skip as much as possible. A short wiki page of the basics, what to do in wich order or some milestones to reach would be great. At the moment there is nothing suffcient.
I've also tried informing myself on YouTube but couldnt find a good video for this.

**Comment by MentalMouse** [comment]
Hexxonite:  That's really an issue for your modpack maker.  But if Prosperity Ore is limited to the outer planets, then your modpacker has decided to gate basically all of the Mystical Agriculture stuff (that is, unlimited farming of resources) behind those planets.  If you're already seeing Inferium, stockpile it; if you can get Soul Sand, make the Soulium Dagger and stockpile mob parts.  Otherwise, you get there when you get there.

**Comment by BlakeBr0** [comment]
The newer versions of this mod now have an ingame guide book provided you have Patchouli installed.
