### ISSUE TITLE
Tertium Farmland consistently yields more crop than Imperium Farmland.

### ISSUE THREAD

**Issue by sutartmelson** [BlakeBr0/MysticalAgriculture#286]
Running the latest release downloaded from forge for 1.15.2.

When harvesting Inferium Essence, Tertium farmland consistently yields more than Imperium farmland. I've attempted to dig through the code, I can't find anything obvious like a swapping of tiers in `block/ModBlocks.java`.

Hopefully someone else can reproduce this bug.

**Comment by erispre** [comment]
I stumbled upon this while trying to determine how Inferium Essence yield could be maximized. It's due to the way `InferiumCropBlock` determines how many crops it should yield. The condition `tier % 2 > 0` should in fact be `tier % 2 == 0`. Otherwise, you would get the following yields:

- Tier 1: 100%
- Tier 2: 100%
- Tier 3: 250%
- Tier 4: 200%
- Tier 5: 350%

Whereas I believe it should be:

- Tier 1: 100%
- Tier 2: 150%
- Tier 3: 200%
- Tier 4: 250%
- Tier 5: 300%

**Comment by sutartmelson** [comment]
I probably spent an hour stepping through that block of code and didn't catch that. Good work @erispre !

**Comment by BlakeBr0** [comment]
Fixed in the latest version.
