### ISSUE TITLE
Growth Accelerators not working on full column above it.

### ISSUE THREAD

**Issue by bbbuddha** [BlakeBr0/MysticalAgriculture#310]
Modpack - All the Mods 5
Minecraft version 1.15
all tiers of growth accelerators only affect the soil and crop directly above it and no others above that crop.

**Comment by BlakeBr0** [comment]
That's intentional.

**Comment by duncanwebb** [comment]
Hope you don't mind if I use this ticket as it is related, if you do then I'll open a new ticket.

Would you be so kind as to explain how the growth accelerators work because as far as I can see they don't do anything? The crops don't seem to grow much faster.  I don't see any growth sparks that indicate accelerated growth, may be not implemented.

The patchoui manual says that plants are affected one level above the accelerator but it doesn't say anything about the different levels of growth accelerators. Do they now act like watering cans, the higher the level the faster and greater area that plants grow?

MysticalAgriculture-1.15.2-3.0.8
Forge 31.2.31

Thanks, I enjoy playing with this mod, it's fun and easy.

**Comment by duncanwebb** [comment]
Something else that is a bit confusing is the dimensions shown in the tool tip of the accelerator blocks, Inferium growth accelerator says if affects 12 blocks, does this mean that the area is 12x12 centred on which block or does it mean that this is a 12 block radius from the with the accelerator block in the centre?
