### ISSUE TITLE
Honey seeds would not grow in Botany pots

### ISSUE THREAD

**Issue by Fungidelight** [BlakeBr0/MysticalAgriculture#318]
Honey seeds cannot be planted in Botany pots - seems to be an issue with Mystical Agriculture rather than Botany pots since all other MA seeds work just fine.

Using mod version 
MysticalAgriculture-1.15.2-3.0.7.jar

**Comment by BlakeBr0** [comment]
All my crops are registered in the same way. If some don't work it's because they aren't adding support in a generic way. I just looked and it seems they add support for each crop manually: https://github.com/Darkhax-Minecraft/BotanyPots/tree/1.15.2/src/main/resources/data/mysticalagriculture/recipes/crops

They could make use of the API to very easily support all crops (including ones added by other mods) if they wanted to.
