### ISSUE TITLE
Supremium Chestplate with Flight Augment added not providing flight [1.16.1]

### ISSUE THREAD

**Issue by ProjectGSX** [BlakeBr0/MysticalAgriculture#367]
**Describe the bug**
I have a Sup. Chestplate with the Flight Augment added and do not have access to flight.

Thanks for maintaining this mod.  I love using it.

**To Reproduce**
Im running Valhesia 3, added MA by hand.  Crafted the Supremium chest plate, crafted the flight augment, combined the two on the tinkers table.

**Expected behavior**
Im expecting that this should allow me to fly.

**Screenshots / Scripts / Logs**
Im not sure what sort of logs to provide.  I can give you a screenshot of the item with the flight augment properly installed if that would be helpful.

**Versions (please complete the following information):**
 - Minecraft: 1.16.1
 - Forge: 32.0.108
 - Cucumber: 4.0.2
 - Mystical Agriculture: 4.0.2

**Comment by glahera** [comment]
Hello, it might be more of Valhelsia's problem due to code conflict between mods (as seen in Valhelsia 2, Midnight's code interfered with many other mods including Immersive Engineering causing its revolver unable to shoot properly). I can try it tonight in my world over on AllTheMod6 modpack to see if it is Mystical Agriculture's bug.

**Comment by dangoodie** [comment]
Hi, I was trying to disable flight with supremium in my server and I cannot find the configurable flight setting either. Were config settings removed in the server files?

**Comment by BlakeBr0** [comment]
I haven't been able to reproduce this with MA on it's own. I'm going to assume this is being caused by another mod.
