### ISSUE TITLE
MA does not recognize that the latest version of DE is installed

### ISSUE THREAD

**Issue by manchesterjm** [BlakeBr0/MysticalAgriculture#444]
**Describe the bug**
MA is supposed to give seeds for Draconic Evolution but it does not recognize that the latest version of DE Draconic-Evolution-1.16.5-3.0.11.396-universal is installed

**To Reproduce**
Steps to reproduce the behavior: Just install the latest version and you will see no seeds for DE

**Expected behavior**
Expected to see DE seeds like Draconium and Awakened Draconium

**Screenshots / Scripts / Logs**
only MA / Cucumber and DE / BrandonsCore installed while testing

**Versions (please complete the following information):**
 - Minecraft:  1.16.5
 - Forge: 36.2.2
 - Cucumber:  4.1.10
 - Mystical Agriculture: 4.2.1

**Comment by AlgorithmLX** [comment]
Hello dear player! DE came out not long ago, and the author MA, how could not know what will happen will come out DE 1.16.5 to the release! Initially, all seeds from DE were in the official addon Mystical Agradditions. This is exactly what the bug is - integration with Astral Sorcery, in which the Rock Crystal seeds cannot be crafted
