### ISSUE TITLE
Soul Jar issue

### ISSUE THREAD

**Issue by Areavate** [BlakeBr0/MysticalAgriculture#451]
**Describe the bug**
Want to make slime spawn egg. Craft soulium dagger enchant it with sharpness V and started to kill some slime with soul jar in the inventory.The soul jar doesn't fill up with slime soul asI kill'em.So I tried with no enchantment and doesn't work too.

**To Reproduce**
Craft soulium dagger and soul jar. Kill the slimes. The jar doesn't fill up.

**Expected behavior**
The jar start filling up

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge: 36.2.0
 - Cucumber:1.16.4-4.1.10.jar
 - Mystical Agriculture:1.16.5-4.2.3.jar

**Comment by BlakeBr0** [comment]
Are you killing vanilla slimes?

**Comment by andyad8865** [comment]
I'm getting a similar issue, despite it being with a modpack with the name of All The Mods 6, 

I'm able to get vanilla slimes to work fine but modded slimes such as the ones from tinkers construct do not work such as a slime island, even if it is a green slime similar to the vanilla kind.

With slimes that spawn from slime islands from tinkers construct it appears that the islands no longer spawn vanilla slimes (green) and blue slimes ect. 

The green slimes spawned from tinkers construct islands are Identified as from tinkers construct and no longer vanilla.

From this it appears that modded slimes such as the green slimes from tinkers construct and soul jars are not able to be used together with the soulium dagger since it is not recognised as a valid mob to be used for the slime soul jar.

An image example of the 2 green slimes from "TheOneProbe":

Vanilla:
![image](https://user-images.githubusercontent.com/25516198/137764364-3cd139ed-d3c1-472a-98a0-a756ffb494d4.png)

Tinkers Construct:
![image](https://user-images.githubusercontent.com/25516198/137764763-a2635a9d-ca31-4d91-b9fb-bd70e2da3077.png)


Minecraft:1.16.5
Forge: 36.2.6
Cucumber:1.16.4-4.1.10
Mystical Agriculture:1.16.5-4.2.3

**Comment by Areavate** [comment]
> Are you killing vanilla slimes?

Same issue of andyad8865

**Comment by Areavate** [comment]
> I'm getting a similar issue, despite it being with a modpack with the name of All The Mods 6,
> 
> I'm able to get vanilla slimes to work fine but modded slimes such as the ones from tinkers construct do not work such as a slime island, even if it is a green slime similar to the vanilla kind.
> 
> With slimes that spawn from slime islands from tinkers construct it appears that the islands no longer spawn vanilla slimes (green) and blue slimes ect.
> 
> The green slimes spawned from tinkers construct islands are Identified as from tinkers construct and no longer vanilla.
> 
> From this it appears that modded slimes such as the green slimes from tinkers construct and soul jars are not able to be used together with the soulium dagger since it is not recognised as a valid mob to be used for the slime soul jar.
> 
> An image example of the 2 green slimes from "TheOneProbe":
> 
> Vanilla: ![image](https://user-images.githubusercontent.com/25516198/137764364-3cd139ed-d3c1-472a-98a0-a756ffb494d4.png)
> 
> Tinkers Construct: ![image](https://user-images.githubusercontent.com/25516198/137764763-a2635a9d-ca31-4d91-b9fb-bd70e2da3077.png)
> 
> Minecraft:1.16.5 Forge: 36.2.6 Cucumber:1.16.4-4.1.10 Mystical Agriculture:1.16.5-4.2.3

If u want a method to bypass this issue for this and future mob u can use the soul extractor from this mod where u put the drop  of the mob of interest and the machine will transform that in essence to put in the souljar,I verified and in the ftb official wiki this block is not mentioned

**Comment by BlakeBr0** [comment]
I'll look into maybe adding that tinkers slime to the default values, though I'm not entirely sure if I want to go down the path of adding modded variants of entities to all of the mob soul types.

As a side note, Mystical Customization has the ability to add entities to mob soul types: https://blakesmods.com/docs/mysticalcustomization/editing-mobsoultypes#entities
