### ISSUE TITLE
Suggestion:  Fill in dye-essence recipes with "generic" dyes.

### ISSUE THREAD

**Issue by MentalMouse** [BlakeBr0/MysticalAgriculture#48]
Obviously, you wouldn't want dye essence to be able to churn out lapis or other "functional" dyes.  But right now, that means you can't produce dyes in those colors at all.  I note that Biomes O'Plenty introduces "generic" dyes for those colors -- for example, a pine cone crafts to a "splotch" of brown dye, which is not a cocoa bean.  Perhaps you could do the same to fill in your spectrum?

Aside:  I see you changed the way dye essence works; whatever, the change has both good and bad points.  Doesn't really change the suggestion.

**Comment by BlakeBr0** [comment]
If I were to do this I would have to manually add recipes for all the non-functional dyes manually because they are always ore dictionary equivalents of the vanilla dyes. Don't really want to, and I don't see a point, considering you can get lapis, cocoa beans, etc from different seeds already.

I changed the recipes because the way they were didn't fit with the rest of the essence recipes, and lots of people prefer it this way.

**Comment by MentalMouse** [comment]
The point is to be able to take a stack of dye essence and have All The Colors.   

Then too, dye seeds are ungated tier 2, while  the "different seeds" for the missing colors range up to Tier 4, one is a mob seed (thus Nether gated), and another requires smelting.

**Comment by MentalMouse** [comment]
CraftTweaker script, using the Biomes O'Plenty dyes: https://pastebin.com/6QeMkDvv
