### ISSUE TITLE
[Suggestion] Upgradable farmlands

### ISSUE THREAD

**Issue by C0rn3j** [BlakeBr0/MysticalAgriculture#492]
Currently, if you make T1 farmland, that T1 resource put in it is wasted if you want to get T2. (or any Tx->Tx+1).

Possible solutions - 

A) Right clicking a Tx Farmland with a Tx+1 resource drops Tx resource and farmland gets upgraded to Tx+1
B) Right clicking a Tx Farmland with 3x Tx resource and then a crystal to finish the upgrade gets the farmland upgraded to Tx+1
C) Harvesting a Tx farmland with silk touch then crafting it with itself, 3x Tx resource and a crystal gets it upgraded

Or is the non-upgradeability intended by design and resources are meant to be wasted during farmland upgrades/reworks?

**Comment by BlakeBr0** [comment]
In more recent versions you can right click on already infused farmland with another essence to upgrade it. There's a 25% chance to get the essence back when doing so or breaking it normally. At this time the potential loss of essence when breaking (without silk touch) or converting between them is by design.
