### ISSUE TITLE
Awakening Altar doesnt works? 1.19.2-6.0.2.

### ISSUE THREAD

**Issue by kevkev1604** [BlakeBr0/MysticalAgriculture#541]
The Awakening Altar doesn't work and i dont know why

I powered it with Redstone and have all stuff for Awakening block put in it 

The altar also shows me the block he would craft on, but nothing happens even after powering redstone. I didn't change anything in the configs

I find nothing in debug ore logs :/ / Are there known mods that corrupt this?

MC: 1.19.2
- Forge: 43.1.25
- Cucumber: Cucumber-1.19.2-6.0.1.jar
- Mystical Agriculture: MysticalAgriculture-1.19.2-6.0.2.jar
- Mystical Agradditions: MysticalAgradditions-1.19.1-6.0.0.jar
-Mystical Customization: MysticalCustomization-1.19.1-4.0.0.jar

I hope u can help me

**Comment by BlakeBr0** [comment]
Do all the essence vessels have the right amount of essences?

**Comment by kevkev1604** [comment]
Yes everything is according to the recipe and in the right order,

**Comment by RealNenzar** [comment]
Same problem for us. The altar shows the finished recipe but the process is not started.

**Comment by kevkev1604** [comment]
yes thats what i mean

**Comment by RealNenzar** [comment]
![javaw_EFxPhBb7vH](https://user-images.githubusercontent.com/63953799/192092015-a143d562-6438-4d44-a535-44e230ccecc3.png)

**Comment by BlakeBr0** [comment]
There should be cognizant dust on all 4 pedestals. Seems like there's an issue with the overlay I will have to look into.

**Comment by James-NULL** [comment]
> There should be cognizant dust on all 4 pedestals. Seems like there's an issue with the overlay I will have to look into.

Came here for the same issue; glad it's already been solved. 
Thank you for the hard work!

Edit: Having issues with other recipes as well. Attempting to awaken my furnace currently and tried the recipe as instructed and I also tried it with dust instead of the 1 Air/Earth. Wondering if it's supposed to be 2 bars and 2 gems.
Edit 2: it is two bars and two gems.
Edit 3: I don't know if these are helping anyone at all, but to anyone else who ends up here for this reason; ignore the top "air" and bottom "earth" essence and just double whatever is on the left and right (one bar and 1 gem = 2 bars and 2 gems and if it says 2 bars do 4 bars) hope this helps until the issue is resolved!

**Comment by PhilGnampf** [comment]
Look here for recipes for me they worked:
https://github.com/BlakeBr0/MysticalAgriculture/tree/1.19/src/main/resources/data/mysticalagriculture/recipes
