### ISSUE TITLE
1.19.2 build (6.0.3) is asking for Cucumber 6.0.2

### ISSUE THREAD

**Issue by Hypocertise** [BlakeBr0/MysticalAgriculture#545]
**Describe the bug**
States version 6.0.2 or higher of cucumber needed when there is only version 6.0.1 on curse ATM

**To Reproduce**
Install MysticalAgg and try to load it

**Expected behavior**
Mod to load with out issue

**Screenshots / Scripts / Logs**
N/A

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.1.32
 - Cucumber: 6.0.1
 - Mystical Agriculture: 6.0.3

**Comment by IsaiahMM** [comment]
I am currently hosting a server utilizing cucumber 6.0.1 and haven't had any issues. Although it seems you're using a different forge version than me. I'm using 43.1.27. Could try to change your forge version but do you have any screenshots of the error you're getting?

**Comment by Zelioth** [comment]
The error is probably where when he updated the mod he changed the version of cucumber required and either has not updated cucumber or didn't mean to change it to that required version. this is an easy fix and I reported the issue because of conflicts of other mods and not being able to launch due to the cucumber core. I posted more info and logs

**Comment by BlakeBr0** [comment]
Submitted new cucumber version to curse.
