### ISSUE TITLE
Antivirus warning (1.19.2)

### ISSUE THREAD

**Issue by DuisPlay** [BlakeBr0/MysticalAgriculture#604]
**Describe the bug**
I got the warning by Windows Defender, that there is a trojan "Trojan:Script/Wacatac.B!ml" in the jar.

**To Reproduce**
Download with Windows Defender enabled

**Expected behavior**
Due to the malware issue with Curseforge, I'm not sure if it's a false positive. It would be great to check if it is virus/trojan free.

**Screenshots / Scripts / Logs**
Sry i have only a warning in german.

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.14
 - Cucumber:
 - Mystical Agriculture: 6.0.10
![Screenshot 2023-06-19 210213](https://github.com/BlakeBr0/MysticalAgriculture/assets/95554907/a640acaa-3dac-471c-925f-8d68172b0e54)

**Comment by zublie** [comment]
Also happened to me

![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/137110443/cebec494-1d82-4bd3-a0df-bd1beed6a9a8)

Update 1.391.1987.0 just came out today for Microsoft defender, I didn't have this happen before this update. I also haven't updated mystical agriculture since the 6/15/2023.  I'm fairly sure its a false positive, scanned it with malware-bytes just to be safe and it didn't pick it up.

**Comment by BlakeBr0** [comment]
It's a false positive. I would guess because of the malware scare that happened on curseforge recently it's being overly cautious
