### ISSUE TITLE
Step Assist not working

### ISSUE THREAD

**Issue by HowardRoark2016** [BlakeBr0/MysticalAgriculture#630]
**Describe the bug**
Step Assist augment not working

**To Reproduce**
Add step assist augment to awakened supremium boots

**Expected behavior**
Cannot step up even a dirt block or oak log while walking or running

**Screenshots / Scripts / Logs**
https://i.imgur.com/6kxNUUm.png

**Versions (please complete the following information):**
 - Minecraft: 1.20.1, ATM9 v65
 - Forge: 47.1.3
 - Cucumber: Cucumber-1.20.1-7.0.1
 - Mystical Agriculture: MysticalAgriculture-1.20.1-7.0.3

**Comment by BlakeBr0** [comment]
Does it work without those enchantments?

**Comment by HowardRoark2016** [comment]
> Does it work without those enchantments?

Step Assist did not work prior to adding those enchantments.

EDIT:

I created another Awakened Supremium Boots and applied nothing but the Step Assist augment to it. I also removed all baubles, etc. I am wearing nothing but the boots and I have no effects applied. Step Assist still does not work whether walking or running.

https://i.imgur.com/hXHnrx7.png

**Comment by BlakeBr0** [comment]
I just tested using that modpack and it seems you're right. I guess a mod in there is constantly resetting the players step height or something, because it worked fine in my dev environment. I'm pretty sure there's a new way I'm supposed to handle this so I'll just switch to that and hopefully that fixes it.
