### ISSUE TITLE
Custom Infusion Recipes Giving Back Ingredients on Completion

### ISSUE THREAD

**Issue by Darkosto** [BlakeBr0/MysticalAgriculture#656]
Hey modder person!

**Is your feature request related to a problem? Please describe.**
Is there a way to setup Infusion recipes but not consume all of the ingredients? I'm trying to setup a recipe that uses a template item and not have the player recraft it every time. Do you know of a way that could be done? It doesn't necesarily have to be the center item, any item in the recipe could work

**Describe the solution you'd like**
A possible way to both receive the output item and an ingredient item

**Describe alternatives you've considered**
I have not found another way in the mod to recreate this feature

**Additional context**
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/10309699/31b07ffa-aad9-4c26-bb7f-ffd76250101b)

**Comment by BlakeBr0** [comment]
The center item can't have a crafting remainder item because the output of the recipe ends up there. As far as the pedestals go, they can have remainder items and should work fine for items that have them. I'm not sure if they work with user-defined remainder items set with ex. CraftTweaker so I'll have to look into that.

Edit: actually I'll add support for remainder items to the center item because it'll work just fine.

**Comment by BlakeBr0** [comment]
I added the ability to use CraftTweaker transforms like `.reuse()` in Infusion/Awakening recipes. I also made it so that remainder items work for the center item in version 7.0.8.
