### ISSUE TITLE
Automating Essence Vessel Causes More Essence Than Intended To Be Used

### ISSUE THREAD

**Issue by wallonfire** [BlakeBr0/MysticalAgriculture#671]
**Describe the bug**
If you have a recipe that uses Less than 40 Essence (Fire, Earth, Air, Water). And put more in the vessel, it consumes all of the essence.
**To Reproduce**
1. Put a number of essence in vessel more than the recipe calls for.
2. Use altar to make desired item
3. Essence vessels are empty.

**Expected behavior**
Just -cost from total not empty.

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Cucumber: 7.0.7
 - Mystical Agriculture: 7.0.9
 - Singleplayer or Multiplayer: Multiplayer, ATM9.0.2.46

**Comment by BlakeBr0** [comment]
If you place the Pedestals and Essence Vessels in the other order (where the Pedestals are placed at each cardinal direction) the items shouldn't get deleted.

I'm going to fix both the order of the ghost pedestals to be the order mentioned above as well as fix the recipe remainder logic to actually account for different arrangements since that is technically allowed.
