### ISSUE TITLE
mystical agriculture modded ingots uncraftable from lithrereal

### ISSUE THREAD

**Issue by Tsumiki129** [BlakeBr0/MysticalAgriculture#676]
wen having MA with Lithereal and a mod that adds ingots the essence cant be crafted to ingots so if having thermal expantion and trying to craft led ingots it wont work with Lithereal instald on minecraft 1.20.1 forge 47.2.20 lithereal on 1.4.0 and up mystical agriculture on 7.0.2 for both single and multyplayer.
jei is in to help show the isues

![2024-02-21_20 11 20](https://github.com/BlakeBr0/MysticalAgriculture/assets/147937268/eda4a316-2fce-4552-9e0b-fd406c16a91c)

![2024-02-21_20 10 27](https://github.com/BlakeBr0/MysticalAgriculture/assets/147937268/adb73003-911c-4766-8d10-1264aa17caff)

**Comment by Devilswarchild** [comment]
Id also like to know what's causing this considering this is happening in my modpack....

**Comment by BlakeBr0** [comment]
Do essence recipes for vanilla items like Iron work? It may be a weird compatibility issue with another mod. Are there any that do any changes to recipe handling?

**Comment by Devilswarchild** [comment]
the reason why we say its something to do with mystical agri and lithereal is bc when we downgrade lithereal back to a state before the 1.4 release everything works fine. but neither me( the modpack dev of minecolonies: dimensional adventure) or the lithereal dev can figure out heads or tails as to why its happening in his 1.4 versions

**Comment by Tsumiki129** [comment]
yes vanilla ones work just fine its only modded ones added wen you have lithereal as well on version 1.4.0 and 1.4.1sp for example iron essence works fine but led from thermal doesn't with lithereal installed but without lithereal or if the mod is downgraded to 1.3.0 it will craft led ingots just fine so we believe somewhere the mod conflicts with litheral to make mudded ingots and essence have issues

**Comment by BlakeBr0** [comment]
I believe [this](https://github.com/LightBlueGamer/Lithereal/blob/master/common/src/main/java/org/lithereal/mixin/ShapedRecipeMixin.java) is the problem since it prevents every single recipe from calling its own `assemble` method and assumes that they all have an item set to the `result` field of ShapedRecipe. Some of the recipes (including the one mentioned in this issue) use my custom recipe type that resolves the output dynamically when `getResultItem` is called. The default implementation of `assemble` calls the `getResultItem` function which does not appear to be the case here.

**Comment by LightBlueGamer** [comment]
Hey thanks for picking that up! I had completely missed that one was looking back and forth in the code but missed that one I've fixed it now appreciate the help!

**Comment by ghost** [comment]
We have fixed the issue in our 1.4.2 release, thank you for letting us know!
