### ISSUE TITLE
Option to allow same augment in config

### ISSUE THREAD

**Issue by EvilDarkSoul** [BlakeBr0/MysticalAgriculture#686]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Describe the solution you'd like**

Add an option in the config to disable the restriction on having multiple augments at the same time.

**Describe alternatives you've considered**

Rather than just a on/off option have a number that determins the number off how many are alloud

**Additional context**

**Comment by BlakeBr0** [comment]
The amount of augments an item can have is based on the tier. Awakened Supremium can have 2 augments.

**Comment by EvilDarkSoul** [comment]
I am refering to having multiple of the same augment on different armour peices and them stacking

**Comment by BlakeBr0** [comment]
Oh I see. I don't think that would work since basically all of them are static effects. If having say multiple speed 2 augments equipped would increase the speed effect level then it would overlap with the speed 3 augment. That would be kind of redundant because that means you are using 2 of your augment slots to get the effect of the speed 3 augment.

**Comment by EvilDarkSoul** [comment]
Yeah ok. I just wanted a way where i could get 8 lots of max health V on a set of armour
