### ISSUE TITLE
Feature Request, Vanilla Crops

### ISSUE THREAD

**Issue by Veggetossj** [BlakeBr0/MysticalAgriculture#8]
Add Nature Essence recipe for the following vanilla crops:
- Beetroot
- Potatoe
- Poisonous Potatoe
- Carrot

Other vanilla crops like melon, pumpkin, wheat and sugarcane already have a recipe with nature essence, it didnt make sense to me why the 4 requested didnt have a recipe

**Comment by BlakeBr0** [comment]
I might remove the ability to make Wheat with nature essence because you get it from a normal crop anyways. If I don't I'll probably add recipes for those crops as well.

**Comment by MentalMouse** [comment]
I'd vote for inclusion.  Half the current recipes, are crops the player needed to have already, just to craft the seed and painstakingly cultivate enough essence to be able to craft anything with it.  AFAICT, the "point" of the essence is to be craftable into any normal plant, so it should certainly have recipes for at least the vanilla crops.  You might even consider a generic crafting recipe to duplicate small plants in general, such as Biomes O'Plenty's many decorative plants and mushrooms.

**Comment by BlakeBr0** [comment]
My idea for the nature essence is for it to be like a 'generic crop' variant of the unconventional crops like Sugarcane.

**Comment by MentalMouse** [comment]
The problem is, how does it compete?  For the current recipe, you already need to have cactus, sugarcane, and pumpkin as well as wheat.  OK, so you get a single farm-plot crop to replace all the nonstandard ones, except you need to find half of them anyway, then breed up your field from nearly scratch at 1.1 seeds per generation.  Meanwhile the original crops are busily growing much faster than the essence, and you have three of them for sure.  I'd say make "nature essence" as flexible and useful as possible.

**Comment by BlakeBr0** [comment]
I'll think about it. Still not sure where I want to go with it.
